version: '3'

services:
  web:
    container_name: digital-twin
    command: yarn start
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://mongo:27017/digitaltwin
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - 27017:27017